version: '3'

services:
  postgresql:
    image: postgres
    restart: on-failure
    environment:
      POSTGRES_DB: go-order-service-db
      POSTGRES_USER: test
      POSTGRES_PASSWORD: secret
    ports:
      - "5440:5432"

  adminer:
    image: adminer
    restart: on-failure
    ports:
      - "8050:8000"